// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhcwenwtygeutvdjsctz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoY3dlbnd0eWdldXR2ZGpzY3R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTY3NDcsImV4cCI6MjA2MTI3Mjc0N30.elpT3qfQK347YjYmdEtpmhP83Fyo48HYcytcrGsK284";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);